name: Deploy Frontend to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to frontend directory
            cd ~/hnx_Frontend
            
            # Fetch and sync the latest frontend files from GitHub
            git pull origin main
            
            # Copy all updated files to the live Nginx directory
            cp -r * /var/www/html/
